### ISSUE TITLE
Can't run prm_planner_node.py

### ISSUE THREAD

**Issue by GuancongLuo** [boschresearch/STAAMS-Solver#1]
Hi, @JKBehrens and @ralph-lange 

I'm a master student  who reseach dual-arm manipulation.And I'm intersting your work and the paper. This is good for my thesis. 

When I try to run your demo code, I get some problem.
Can't execution `self.exp_obj = ovc_experiment(name="created_in_subprocess")`
![Screenshot from 2019-10-31 17-09-52](https://user-images.githubusercontent.com/41011340/67933691-4ab42e80-fc01-11e9-9e46-437029cfa3c7.png)

Can't correct import modules.
![Screenshot from 2019-10-31 16-50-52](https://user-images.githubusercontent.com/41011340/67933114-27d54a80-fc00-11e9-8206-6998adda5cdf.png)

After I check the whole code, I find this repo miss some module e.g. kinematics_interface_kuka.

Can't you get me some suggestion to represent this paper?

**Comment by ralph-lange** [comment]
Hello @GuancongLuo 

@JKBehrens will answer this issue in his fork at https://github.com/JKBehrens/STAAMS-Solver/
